import { Hono } from 'hono';
import { readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexHtml = readFileSync(join(__dirname, '../../index.html'), 'utf8');

const legal = new Hono();

const wrapHtml = (title: string, content: string) => `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title} - DJD Agent Score</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; line-height: 1.7; }
  h1 { font-size: 28px; margin-top: 40px; margin-bottom: 16px; color: #111; }
  h2 { font-size: 22px; margin-top: 32px; margin-bottom: 12px; color: #222; }
  p { margin-bottom: 16px; font-size: 15px; }
  .title { text-align: center; margin-bottom: 8px; font-size: 32px; }
  .subtitle { text-align: center; margin-bottom: 8px; font-size: 26px; }
  .date { text-align: center; font-style: italic; margin-bottom: 40px; color: #666; }
  .caps { text-transform: uppercase; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { border: 1px solid #ddd; padding: 10px 12px; font-size: 14px; text-align: left; }
  th { background: #2B3544; color: #fff; font-weight: 600; }
  tr:nth-child(even) { background: #f9f9f9; }
  .footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 13px; color: #888; }
</style>
</head>
<body>${content}
<div class="footer">DJD Agent Score &middot; Trust infrastructure for the agent economy</div>
</body>
</html>`;

// ─── TERMS OF SERVICE ───

const tosContent = `
<h1 class="title">DJD AGENT SCORE</h1>
<h1 class="subtitle">TERMS OF SERVICE</h1>
<p class="date">Last Updated: February 20, 2026</p>

<p>These Terms of Service (&ldquo;<strong>Terms</strong>&rdquo;) govern your access to and use of the DJD Agent Score API and related services (the &ldquo;<strong>Service</strong>&rdquo;), operated by DJD Agent Score (&ldquo;<strong>Company,</strong>&rdquo; &ldquo;<strong>we,</strong>&rdquo; &ldquo;<strong>our</strong>&rdquo;). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.</p>

<h1>1. Description of Service</h1>
<p>DJD Agent Score is an experimental reputation scoring API for autonomous AI agent wallets on the Base blockchain. The Service provides trust scores, fraud reports, and related data products, accessible via HTTP endpoints and payable through the x402 micropayment protocol using USDC.</p>

<h1>2. Experimental Status</h1>
<p><strong>The Service is experimental.</strong> All scores, tiers, recommendations, confidence intervals, and related outputs are generated by an unvalidated algorithmic model based on publicly available on-chain data. Scores are informational only. They are not financial advice, credit assessments, consumer reports, investment recommendations, or guarantees of any kind.</p>
<p>The scoring model, its weights, its data sources, and its methodology may change at any time without notice. Model version information is included in every API response for transparency.</p>

<h1>3. No Warranty; Limitation of Liability</h1>
<p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, OR NON-INFRINGEMENT.</p>
<p>We do not warrant that scores are accurate, complete, reliable, current, or error-free. We do not warrant that the Service will be uninterrupted, secure, or free of bugs or vulnerabilities.</p>
<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS OFFICERS, DIRECTORS, MEMBERS, EMPLOYEES, OR AGENTS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, WHETHER IN AN ACTION IN CONTRACT, TORT, OR OTHERWISE, ARISING OUT OF OR RELATING TO YOUR USE OF OR INABILITY TO USE THE SERVICE.</p>
<p>OUR TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE TOTAL AMOUNT YOU PAID TO US IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.</p>

<h1>4. Assumption of Risk</h1>
<p>You acknowledge and agree that:</p>
<p>(a) You use the Service at your own risk. Scores are algorithmically generated and may be inaccurate, incomplete, or misleading.</p>
<p>(b) You will not rely solely on any DJD Agent Score output to make financial, contractual, or transactional decisions.</p>
<p>(c) The agent economy is nascent, and the Service operates in an environment with significant uncertainty, technical risk, and regulatory ambiguity.</p>
<p>(d) Blockchain transactions are irreversible. We are not responsible for any losses resulting from transactions you enter into after reviewing a score.</p>

<h1>5. Fraud Reports</h1>
<p>The Service accepts user-submitted fraud reports through the POST /v1/report endpoint. You acknowledge and agree that:</p>
<p>(a) Fraud reports are unverified third-party submissions. We do not independently investigate, confirm, or validate the accuracy of any fraud report.</p>
<p>(b) Submission of a fraud report may result in a score penalty applied to the target wallet. This penalty is automated and does not constitute an accusation, finding, or determination of wrongdoing by the Company.</p>
<p>(c) If you submit a fraud report, you represent that the information provided is truthful and accurate to the best of your knowledge. Submitting knowingly false or malicious reports is a violation of these Terms and may result in penalties to your own wallet&rsquo;s score.</p>
<p>(d) The Company is not liable for any damages arising from fraud reports, whether accurate or inaccurate, including but not limited to reputational harm, economic loss, or reduced access to third-party services.</p>

<h1>6. No Reliance; Independent Judgment; FCRA Disclaimer</h1>
<p>The Service does not provide and should not be construed as providing legal, financial, investment, tax, or professional advice of any kind. You are solely responsible for your own due diligence and decision-making. The Company expressly disclaims any responsibility for decisions made in reliance on Service outputs.</p>
<p>The Service is not a &ldquo;consumer report&rdquo; as defined by the Fair Credit Reporting Act (15 U.S.C. &sect; 1681 et seq.) or any equivalent state law. Scores are not intended to be used as a factor in determining eligibility for credit, insurance, employment, or any other purpose regulated by the FCRA. The Company is not a &ldquo;consumer reporting agency&rdquo; as defined by the FCRA.</p>

<h1>7. Payments and Fees</h1>
<p>Certain endpoints require payment via the x402 micropayment protocol using USDC on the Base blockchain. Prices are displayed in each API response&rsquo;s 402 challenge. All payments are non-refundable. Payment does not create any warranty, guarantee, or obligation beyond delivery of the requested API response.</p>
<p>The free tier (10 basic lookups per day per requester) may be modified or discontinued at any time.</p>

<h1>8. Data Collection and Use</h1>
<p>By using the Service, you acknowledge that we collect and store:</p>
<p>(a) API query data, including requester wallet address, target wallet address, endpoint requested, timestamp, and response metadata.</p>
<p>(b) Publicly available on-chain data from the Base blockchain, including transaction history, wallet balances, and smart contract state.</p>
<p>(c) User-submitted data, including fraud reports, ratings, and dispute information.</p>
<p>We may use aggregated and anonymized data for analytics, reporting, research, model improvement, and commercial data products. Individual wallet addresses are blockchain-native public identifiers and are not treated as personally identifiable information.</p>

<h1>9. Intellectual Property</h1>
<p>All scoring algorithms, data models, aggregated datasets, analytical outputs, and related intellectual property are the exclusive property of the Company. You may not reverse-engineer the scoring model, scrape the API for the purpose of building a competing service, or use API outputs as training data for competing scoring systems without our prior written consent.</p>
<p>API responses may be cached locally for up to one (1) hour. Any public display of DJD Agent Score data must include attribution to &ldquo;DJD Agent Score&rdquo; with a link to the Service.</p>

<h1>10. Prohibited Uses</h1>
<p>You agree not to:</p>
<p>(a) Use the Service to harass, defame, or cause harm to any individual or entity.</p>
<p>(b) Submit false, misleading, or malicious fraud reports.</p>
<p>(c) Attempt to manipulate scores through Sybil attacks, wash trading, or other artificial means.</p>
<p>(d) Exceed rate limits or circumvent free-tier restrictions.</p>
<p>(e) Use the Service in violation of any applicable law or regulation.</p>
<p>(f) Scrape, copy, or redistribute API outputs for the purpose of creating a competing service.</p>

<h1>11. Indemnification</h1>
<p>You agree to indemnify, defend, and hold harmless the Company and its officers, directors, members, employees, and agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys&rsquo; fees) arising out of or relating to: (a) your use of the Service; (b) your violation of these Terms; (c) your reliance on any score or Service output; or (d) any fraud report you submit.</p>

<h1>12. Dispute Resolution; Arbitration</h1>
<p>Any dispute, controversy, or claim arising out of or relating to these Terms or the Service shall be resolved exclusively by binding arbitration administered by JAMS under its Streamlined Arbitration Rules and Procedures. The arbitration shall be conducted in New York, New York, by a single arbitrator. The arbitrator&rsquo;s decision shall be final and binding and may be entered as a judgment in any court of competent jurisdiction.</p>
<p><strong>CLASS ACTION WAIVER:</strong> YOU AGREE THAT ANY DISPUTE RESOLUTION PROCEEDINGS WILL BE CONDUCTED ONLY ON AN INDIVIDUAL BASIS AND NOT IN A CLASS, CONSOLIDATED, OR REPRESENTATIVE ACTION.</p>

<h1>13. Governing Law</h1>
<p>These Terms shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions.</p>

<h1>14. Modification of Terms</h1>
<p>We reserve the right to modify these Terms at any time. Updated Terms will be posted at the Service&rsquo;s domain. Your continued use of the Service after any modification constitutes acceptance of the updated Terms. Material changes will be reflected in the &ldquo;Last Updated&rdquo; date above.</p>

<h1>15. Termination</h1>
<p>We may suspend or terminate your access to the Service at any time, for any reason or no reason, without notice or liability. Upon termination, all provisions of these Terms which by their nature should survive shall survive, including but not limited to warranty disclaimers, limitation of liability, indemnification, and dispute resolution.</p>

<h1>16. Severability</h1>
<p>If any provision of these Terms is held to be invalid or unenforceable, the remaining provisions shall continue in full force and effect.</p>

<h1>17. Entire Agreement</h1>
<p>These Terms constitute the entire agreement between you and the Company regarding the Service and supersede all prior agreements and understandings.</p>

<h1>18. Contact</h1>
<p>For questions regarding these Terms, contact: feedback@djd-agent-score.fly.dev</p>
`;

// ─── PRIVACY POLICY ───

const privacyContent = `
<h1 class="title">DJD AGENT SCORE</h1>
<h1 class="subtitle">PRIVACY POLICY</h1>
<p class="date">Last Updated: February 20, 2026</p>

<p>This Privacy Policy describes how DJD Agent Score (&ldquo;<strong>Company,</strong>&rdquo; &ldquo;<strong>we,</strong>&rdquo; &ldquo;<strong>our</strong>&rdquo;) collects, uses, stores, and discloses information in connection with the DJD Agent Score API and related services (the &ldquo;<strong>Service</strong>&rdquo;). By using the Service, you acknowledge and agree to this Privacy Policy.</p>

<h1>1. Nature of Data Collected</h1>
<p>The Service operates in the blockchain and autonomous agent ecosystem. The primary identifiers used by the Service are public blockchain wallet addresses. Wallet addresses are cryptographic public keys published on the Base blockchain and are not, by themselves, personally identifiable information (&ldquo;<strong>PII</strong>&rdquo;). However, we recognize that wallet addresses may become linked to identifiable individuals through external means. We treat all data with appropriate care regardless of classification.</p>

<h1>2. Information We Collect</h1>

<h2>2.1 Blockchain Data (Public, Passively Indexed)</h2>
<p>We continuously index publicly available data from the Base blockchain, including USDC transfer events (sender, receiver, amount, block number, timestamp), wallet balances, smart contract state related to agent identity registrations (ERC-8004), and transaction patterns. This data is publicly accessible to anyone operating a blockchain node. Our collection adds no new exposure; we structure and analyze what is already public.</p>

<h2>2.2 API Query Data (Collected on Use)</h2>
<p>When you interact with the Service, we collect:</p>

<table>
<tr><th>Data Point</th><th>Source</th><th>Purpose</th></tr>
<tr><td>Requester wallet address</td><td>x402 payment signature or request header</td><td>Query logging, rate limiting, free tier tracking</td></tr>
<tr><td>Target wallet address</td><td>Query parameter</td><td>Score delivery, demand analytics</td></tr>
<tr><td>Endpoint and tier requested</td><td>HTTP request path</td><td>Service delivery, usage analytics</td></tr>
<tr><td>Timestamp</td><td>Server clock</td><td>Rate limiting, analytics, audit</td></tr>
<tr><td>Response time</td><td>Server measurement</td><td>Performance monitoring</td></tr>
<tr><td>User-Agent string</td><td>HTTP header</td><td>Client identification, middleware telemetry</td></tr>
<tr><td>IP address (hashed)</td><td>Network connection</td><td>Free tier identification for non-wallet requests</td></tr>
<tr><td>Payment amount</td><td>x402 transaction</td><td>Revenue tracking, free tier flag</td></tr>
</table>

<h2>2.3 User-Submitted Data</h2>
<p>When you submit fraud reports, ratings, or other content through the Service, we collect the content of your submission, the submitting wallet address, the target wallet address, supporting evidence (transaction hashes), and timestamps. All user-submitted data is voluntary.</p>

<h2>2.4 Information We Do NOT Collect</h2>
<p>We do not collect names, email addresses, phone numbers, physical addresses, government identification numbers, biometric data, or any traditional PII. We do not use cookies, tracking pixels, or browser fingerprinting. We do not integrate with advertising networks. The Service does not have user accounts, logins, or passwords.</p>

<h1>3. How We Use Information</h1>
<p><strong>Service delivery:</strong> Calculating reputation scores, processing fraud reports, generating leaderboards, and serving API responses.</p>
<p><strong>Model improvement:</strong> Analyzing query patterns, score outcomes, and transaction data to validate and improve the scoring model.</p>
<p><strong>Integrity systems:</strong> Detecting Sybil attacks, gaming attempts, and fraudulent behavior through pattern analysis.</p>
<p><strong>Analytics and reporting:</strong> Generating aggregated, anonymized reports on agent economy activity, transaction volumes, and ecosystem health.</p>
<p><strong>Data products:</strong> Creating commercial data products including economy reports, fraud intelligence feeds, intent signal reports, and relationship graph analyses. Individual wallet behavior may be included in aggregate datasets but is not sold as individually targeted profiles.</p>
<p><strong>Research:</strong> Contributing to understanding of autonomous agent ecosystems, on-chain reputation systems, and trust infrastructure.</p>

<h1>4. Data Retention</h1>
<p>Blockchain data (transaction history, wallet balances, relationship graphs) is retained indefinitely. This data is publicly available on the blockchain regardless of our retention practices.</p>
<p>API query logs are retained indefinitely for model validation, analytics, and intent signal analysis. Query logs are the basis for outcome tracking, which requires historical comparison over periods of 30 days or more.</p>
<p>Score history and decay curves are retained indefinitely. Historical score data is a core data product and a key component of the Service&rsquo;s value proposition.</p>
<p>Fraud reports are retained indefinitely. Reports are training data for fraud detection models and form a permanent part of the fraud intelligence corpus.</p>
<p>We do not offer deletion of blockchain-derived data, as it is publicly available and independently verifiable. For user-submitted data (fraud reports, ratings), contact us to discuss specific removal requests.</p>

<h1>5. Data Sharing and Disclosure</h1>
<p><strong>Aggregated and anonymized data:</strong> We may sell or license aggregated, anonymized datasets, analytics reports, and economy metrics to third parties including researchers, investors, platforms, and enterprise customers. These datasets describe ecosystem-level trends, not individual wallet-level targeting.</p>
<p><strong>Per-query data products:</strong> Certain paid API endpoints return data about specific wallets, including scores, fraud report status, relationship data, and decay curves. This data is derived from public blockchain activity and user-submitted reports.</p>
<p><strong>Legal compliance:</strong> We may disclose data if required to do so by law, regulation, legal process, or governmental request, or if we believe in good faith that disclosure is necessary to protect our rights, your safety, or the safety of others.</p>
<p><strong>Business transfers:</strong> In the event of a merger, acquisition, or sale of assets, data collected by the Service may be transferred to the acquiring entity.</p>
<p>We do not sell individual-level data to advertisers. We do not share data with advertising networks. We do not use data for targeted advertising.</p>

<h1>6. Data Security</h1>
<p>We implement commercially reasonable security measures to protect data stored by the Service, including encrypted connections (HTTPS/TLS) for all API communications, access controls on our infrastructure, and secure key management for blockchain interactions. However, no system is perfectly secure, and we cannot guarantee the absolute security of your data. The Service runs on third-party cloud infrastructure (Conway Cloud), and we are subject to that provider&rsquo;s security practices.</p>

<h1>7. International Data</h1>
<p>The Service may be accessed from anywhere in the world. Data is processed and stored on servers located in the United States. By using the Service, you consent to the transfer and processing of data in the United States. If you are located in the European Economic Area, United Kingdom, or other jurisdiction with data protection laws, you acknowledge that blockchain wallet addresses may or may not constitute personal data under your local law, and that publicly available blockchain data presents unique challenges for traditional data protection frameworks.</p>

<h1>8. GDPR and Data Subject Rights</h1>
<p>If you are located in the European Economic Area or United Kingdom and believe that data processed by the Service constitutes your personal data under GDPR or UK GDPR, you may have rights including access, rectification, erasure, restriction of processing, data portability, and objection. Please note:</p>
<p>(a) Blockchain data is publicly available and cannot be erased by any single party. A request to delete blockchain-derived data from our database does not delete it from the blockchain.</p>
<p>(b) Score calculations are algorithmic outputs derived from public data, not personal data collected from you.</p>
<p>(c) We will make reasonable efforts to accommodate valid data subject requests where technically feasible and where the data in question constitutes personal data under applicable law.</p>
<p>To submit a data subject request, contact us at the address listed in Section 12.</p>

<h1>9. California Privacy Rights (CCPA)</h1>
<p>If you are a California resident, the California Consumer Privacy Act may provide you with additional rights regarding data collected about you. Given that the Service primarily processes blockchain wallet addresses (which are not traditionally classified as personal information under CCPA) and does not collect names, email addresses, or other conventional identifiers, the applicability of CCPA to the Service is uncertain. We do not sell personal information as defined by CCPA. If you believe CCPA applies to your use of the Service, contact us to discuss your rights.</p>

<h1>10. Children</h1>
<p>The Service is not directed at individuals under the age of 18. We do not knowingly collect information from minors. The Service does not collect age-related information of any kind.</p>

<h1>11. Changes to This Policy</h1>
<p>We may update this Privacy Policy at any time. Changes will be posted at the Service&rsquo;s domain with an updated &ldquo;Last Updated&rdquo; date. Your continued use of the Service after changes are posted constitutes acceptance of the revised policy. Material changes will be noted prominently.</p>

<h1>12. Contact</h1>
<p>For questions, concerns, or data subject requests regarding this Privacy Policy, contact:</p>
<p>DJD Agent Score<br>feedback@djd-agent-score.fly.dev</p>
`;

const leaderboardHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Leaderboard - DJD Agent Score</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; background: #0f1117; color: #e1e4e8; min-height: 100vh; }
    header { background: #161b22; border-bottom: 1px solid #21262d; padding: 16px 24px; display: flex; align-items: center; gap: 12px; }
    .logo { font-size: 18px; font-weight: 700; color: #fff; text-decoration: none; }
    .logo span { color: #58a6ff; }
    nav { margin-left: auto; display: flex; gap: 20px; }
    nav a { color: #8b949e; font-size: 14px; text-decoration: none; }
    nav a:hover { color: #e1e4e8; }
    main { max-width: 960px; margin: 0 auto; padding: 40px 24px; }
    h1 { font-size: 28px; font-weight: 700; margin-bottom: 6px; }
    .subtitle { color: #8b949e; font-size: 15px; margin-bottom: 32px; }
    .stats { display: flex; gap: 16px; margin-bottom: 32px; flex-wrap: wrap; }
    .stat { background: #161b22; border: 1px solid #21262d; border-radius: 8px; padding: 16px 20px; min-width: 140px; }
    .stat-value { font-size: 28px; font-weight: 700; color: #58a6ff; }
    .stat-label { font-size: 13px; color: #8b949e; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; background: #161b22; border: 1px solid #21262d; border-radius: 8px; overflow: hidden; }
    thead th { background: #1c2128; color: #8b949e; font-size: 12px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; padding: 12px 16px; text-align: left; border-bottom: 1px solid #21262d; }
    tbody tr { border-top: 1px solid #21262d; transition: background 0.1s; }
    tbody tr:hover { background: #1c2128; }
    td { padding: 12px 16px; font-size: 14px; vertical-align: middle; }
    .rank { color: #8b949e; font-weight: 600; width: 48px; }
    .rank-1 { color: #ffd700; }
    .rank-2 { color: #c0c0c0; }
    .rank-3 { color: #cd7f32; }
    .wallet { font-family: 'SF Mono', 'Consolas', monospace; font-size: 13px; color: #58a6ff; cursor: pointer; user-select: none; }
    .wallet:hover { text-decoration: underline; }
    .copy-msg { color: #3fb950; font-size: 11px; margin-left: 6px; opacity: 0; transition: opacity 0.2s; }
    .copy-msg.show { opacity: 1; }
    .score-cell { display: flex; align-items: center; gap: 10px; }
    .score-num { font-weight: 700; font-size: 16px; min-width: 28px; }
    .score-bar-bg { flex: 1; height: 6px; background: #21262d; border-radius: 3px; max-width: 80px; }
    .score-bar { height: 100%; border-radius: 3px; }
    .tier { font-size: 12px; font-weight: 600; padding: 3px 8px; border-radius: 12px; white-space: nowrap; display: inline-block; }
    .tier-Elite    { background: rgba(255,215,0,0.12);   color: #ffd700; border: 1px solid rgba(255,215,0,0.25); }
    .tier-Trusted  { background: rgba(31,111,235,0.12);  color: #58a6ff; border: 1px solid rgba(31,111,235,0.25); }
    .tier-Emerging { background: rgba(35,134,54,0.12);   color: #3fb950; border: 1px solid rgba(35,134,54,0.25); }
    .tier-Unverified { background: rgba(139,148,158,0.08); color: #8b949e; border: 1px solid rgba(139,148,158,0.15); }
    .badges { display: flex; gap: 4px; flex-wrap: wrap; }
    .badge { font-size: 11px; padding: 2px 6px; border-radius: 4px; white-space: nowrap; }
    .badge-reg { background: rgba(86,211,100,0.1); color: #56d364; border: 1px solid rgba(86,211,100,0.2); }
    .badge-gh  { background: rgba(139,148,158,0.1); color: #8b949e; border: 1px solid rgba(139,148,158,0.2); }
    .age { color: #8b949e; font-size: 13px; }
    .loading, .error-msg { text-align: center; padding: 60px 24px; color: #8b949e; font-size: 15px; }
    .error-msg { color: #f85149; }
    .updated { font-size: 12px; color: #484f58; margin-top: 14px; text-align: right; }
    footer { text-align: center; padding: 40px 24px; color: #484f58; font-size: 13px; border-top: 1px solid #21262d; margin-top: 48px; }
    footer a { color: #484f58; text-decoration: none; }
    footer a:hover { color: #8b949e; }
    @media (max-width: 640px) {
      .score-bar-bg, .age, .badges { display: none; }
      td, th { padding: 10px 10px; }
    }
  </style>
</head>
<body>
  <header>
    <a class="logo" href="/">DJD <span>Agent Score</span></a>
    <nav>
      <a href="/v1/leaderboard">JSON</a>
      <a href="/terms">Terms</a>
      <a href="/privacy">Privacy</a>
    </nav>
  </header>
  <main>
    <h1>Agent Leaderboard</h1>
    <p class="subtitle">Top AI agent wallets ranked by reputation score on Base</p>
    <div class="stats" id="stats"></div>
    <div id="table-wrap"><div class="loading">Loading…</div></div>
    <p class="updated" id="updated"></p>
  </main>
  <footer>
    DJD Agent Score &middot; Trust infrastructure for the agent economy &middot;
    <a href="/v1/leaderboard">API</a> &middot; <a href="/terms">Terms</a>
  </footer>
  <script>
    function scoreColor(s) {
      if (s >= 70) return '#1f6feb';
      if (s >= 40) return '#9e6a03';
      return '#238636';
    }
    async function load() {
      try {
        const res = await fetch('/v1/leaderboard');
        if (!res.ok) throw new Error(res.status);
        const data = await res.json();
        const { leaderboard, totalAgentsScored, totalAgentsRegistered, lastUpdated } = data;
        document.getElementById('stats').innerHTML =
          stat(leaderboard.length, 'Ranked agents') +
          stat(totalAgentsScored, 'Total scored') +
          stat(totalAgentsRegistered, 'Registered');
        const rows = leaderboard.map(e => {
          const short = e.wallet.slice(0,6) + '&hellip;' + e.wallet.slice(-4);
          const rc = e.rank <= 3 ? 'rank-' + e.rank : '';
          const age = e.daysAlive >= 30 ? '30d+' : e.daysAlive + 'd';
          const color = scoreColor(e.score);
          const bdgs = [
            e.isRegistered ? '<span class="badge badge-reg">&#10003; registered</span>' : '',
            e.githubVerified ? '<span class="badge badge-gh">&#9864; github</span>' : '',
          ].filter(Boolean).join('');
          return '<tr>' +
            '<td class="rank ' + rc + '">' + e.rank + '</td>' +
            '<td><span class="wallet" data-addr="' + e.wallet + '" onclick="cp(this)">' + short + '</span>' +
            '<span class="copy-msg" id="cm' + e.rank + '">copied</span></td>' +
            '<td><div class="score-cell"><span class="score-num">' + e.score + '</span>' +
            '<div class="score-bar-bg"><div class="score-bar" style="width:' + e.score + '%;background:' + color + '"></div></div></div></td>' +
            '<td><span class="tier tier-' + e.tier + '">' + e.tier + '</span></td>' +
            '<td class="age">' + age + '</td>' +
            '<td><div class="badges">' + bdgs + '</div></td>' +
            '</tr>';
        }).join('');
        document.getElementById('table-wrap').innerHTML =
          '<table><thead><tr>' +
          '<th>#</th><th>Wallet</th><th>Score</th><th>Tier</th><th>Age</th><th>Signals</th>' +
          '</tr></thead><tbody>' + rows + '</tbody></table>';
        const d = new Date(lastUpdated);
        document.getElementById('updated').textContent = 'Last updated: ' + d.toLocaleString();
      } catch(e) {
        document.getElementById('table-wrap').innerHTML = '<div class="error-msg">Failed to load leaderboard.</div>';
      }
    }
    function stat(val, label) {
      return '<div class="stat"><div class="stat-value">' + val + '</div><div class="stat-label">' + label + '</div></div>';
    }
    function cp(el) {
      const addr = el.dataset.addr;
      navigator.clipboard.writeText(addr).then(() => {
        const msg = el.nextElementSibling;
        msg.classList.add('show');
        setTimeout(() => msg.classList.remove('show'), 1500);
      });
    }
    load();
  </script>
</body>
</html>`;

legal.get('/', (c) => c.html(indexHtml));

legal.get('/leaderboard', (c) => c.html(leaderboardHtml));

legal.get('/terms', (c) => {
  return c.html(wrapHtml('Terms of Service', tosContent));
});

legal.get('/privacy', (c) => {
  return c.html(wrapHtml('Privacy Policy', privacyContent));
});

export default legal;
